--Formato padrao para data
ALTER SESSION SET NLS_DATE_FORMAT='YYYY-MM-DD';


-- COLOCAR NOT NULL
-- REGEX PARA E MAIL
-- Tabela Administrador
CREATE TABLE Administrador (
    Email VARCHAR2(32) NOT NULL,
    Username VARCHAR2(32) NOT NULL,
    Senha VARCHAR2(32) NOT NULL,
    Nome VARCHAR2(32),
    Data_Nascimento DATE,
    CONSTRAINT CK_email CHECK (REGEXP_LIKE (Email, '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')),
    CONSTRAINT PK_Administrador PRIMARY KEY (Email)
);

-- Tabela Cliente
CREATE TABLE Cliente (
    Email VARCHAR2(32) NOT NULL,
    Username VARCHAR2(32) NOT NULL,
    Senha VARCHAR2(32) NOT NULL,
    Nome VARCHAR2(32),
    Data_Nascimento DATE,
    Nivel_Conhecimento VARCHAR2(13),
    Precisa_De_Atendimento NUMBER(1,0),
    CONSTRAINT CK_email CHECK (REGEXP_LIKE (Email, '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')),
    CONSTRAINT CK_Nivel_conhecimento CHECK(Nivel_Conhecimento IN ('Iniciante','Intermediario','Avancado')),
    CONSTRAINT PK_Cliente PRIMARY KEY (Email)
);

-- Tabela Voluntario
CREATE TABLE Voluntario (
    Email VARCHAR2(32) NOT NULL,
    Username VARCHAR2(32) NOT NULL,
    Senha VARCHAR2(32) NOT NULL,
    Nome VARCHAR2(32),
    Data_Nascimento DATE,
    CONSTRAINT CK_email CHECK (REGEXP_LIKE (Email, '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$')),
    CONSTRAINT PK_Voluntario PRIMARY KEY (Email)
);


-- Tabela Banimento
CREATE TABLE Banimento (
    Data_Hora DATE NOT NULL,
    Administrador_Email VARCHAR2(32) NOT NULL,
    Voluntario_Email VARCHAR2(32) NOT NULL,
    Motivo VARCHAR2(128),
    Duracao TIMESTAMP,
    CONSTRAINT PK_Banimneto PRIMARY KEY (Data_Hora, Voluntario_Email),
    FOREIGN KEY (Administrador_Email) REFERENCES Administrador(Email)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Voluntario_Email) REFERENCES Voluntario(Email)
        ON	DELETE	CASCADE
);

-- Tabela Capacidades
CREATE TABLE Capacidades (
    Voluntario_Email VARCHAR2(32) NOT NULL,
    Capacidade VARCHAR2(32) NOT NULL,
    CONSTRAINT PK_Capacidades PRIMARY KEY (Voluntario_Email, Capacidade),
    FOREIGN KEY (Voluntario_Email) REFERENCES Voluntario(Email)
        ON	DELETE	CASCADE
);

-- Tabela Modulo
CREATE TABLE Modulo (
    Tema VARCHAR2(16) NOT NULL,
    Administrador_Email VARCHAR2(32) NOT NULL,
    CONSTRAINT PK_Modulo PRIMARY KEY (Tema),
    FOREIGN KEY (Administrador_Email) REFERENCES Administrador(Email)
);

-- Tabela Cursa
CREATE TABLE Cursa (
    Cliente_Email VARCHAR2(32) NOT NULL,
    Modulo_Tema VARCHAR2(32) NOT NULL,
    Porcentagem_Progresso DECIMAL(4,2),
    CONSTRAINT PK_Cursa PRIMARY KEY (Cliente_Email, Modulo_Tema),
    FOREIGN KEY (Cliente_Email) REFERENCES Cliente(Email)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Modulo_Tema) REFERENCES Modulo(Tema)
        ON	DELETE	CASCADE
);

-- Tabela Video Aula
CREATE TABLE VideoAula (
    Modulo_Tema VARCHAR2(32) NOT NULL,
    Topico VARCHAR2(32) NOT NULL,
    Descricao VARCHAR2(512),
    Tempo INT,
    Url_video VARCHAR2(128),
    CONSTRAINT PK_VideoAula PRIMARY KEY (Modulo_Tema, Topico),
    FOREIGN KEY (Modulo_Tema) REFERENCES Modulo(Tema)
        ON	DELETE	CASCADE
);

-- CONTRAINT EXPLICITAS
-- Tabela Avalia
CREATE TABLE Avalia (
    Cliente_Email VARCHAR2(32) NOT NULL,
    Video_Tema VARCHAR2(32) NOT NULL,
    Video_Topico VARCHAR2(32) NOT NULL,
    Nota NUMBER,
    CONSTRAINT CK_nota CHECK(Nota BETWEEN 0 AND 10), 
    PRIMARY KEY (Cliente_Email, Video_Tema, Video_Topico),
    FOREIGN KEY (Cliente_Email) REFERENCES Cliente(Email)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Video_Tema , Video_Topico) REFERENCES VideoAula(Modulo_Tema, Topico)
        ON	DELETE	CASCADE
);

-- Tabela Atendimento
CREATE TABLE Atendimento (
    Data_Hora DATE NOT NULL,
    Cliente_Email VARCHAR2(32) NOT NULL,
    Voluntario_Email VARCHAR2(32) NOT NULL,
    Nota NUMBER,
    CONSTRAINT PK_Atendimento PRIMARY KEY (Data_Hora, Cliente_Email),
    CONSTRAINT CK_Nota CHECK(Nota BETWEEN 0 AND 10),
    FOREIGN KEY (Cliente_Email) REFERENCES Cliente(Email)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Voluntario_Email) REFERENCES Voluntario(Email)
        ON	DELETE	CASCADE
);

-- Tabela Teste
CREATE TABLE Teste (
    Modulo_Tema VARCHAR2(32) NOT NULL,
    Numero INT NOT NULL,
    Nivel_Dificuldade VARCHAR2(13) NOT NULL,
    Tempo_para_completar INTERVAL DAY TO SECOND NOT NULL,
    CONSTRAINT PK_Teste PRIMARY KEY (Modulo_Tema, Numero),
    FOREIGN KEY (Modulo_Tema) REFERENCES Modulo(Tema)
        ON	DELETE	CASCADE
);

-- Tabela Resultado
CREATE TABLE Resultado (
    Id_resultado NUMBER GENERATED by default on null as IDENTITY,
    Cliente_Email VARCHAR2(32),
    Teste_Tema VARCHAR2(16),
    Teste_Numero NUMBER,
    Data_Hora DATE,
    Mensagem_Feedback VARCHAR2(256),
    Aprovacao NUMBER(1,0),
    CONSTRAINT UNQ_Resultado UNIQUE(Cliente_Email, Teste_Tema, Teste_Numero, Data_Hora),
    CONSTRAINT PK_Resultado PRIMARY KEY (Id_resultado),
    FOREIGN KEY (Cliente_Email) REFERENCES Cliente(Email)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Teste_Tema, Teste_Numero) REFERENCES Teste(Modulo_Tema,Numero)
        ON	DELETE	CASCADE
);

-- Tabela Questao
CREATE TABLE Questao (
    Id_questao NUMBER GENERATED by default on null as IDENTITY,
    Topico VARCHAR2(64) NOT NULL,
    Teste_Tema VARCHAR2(16) NOT NULL,
    Teste_Numero INT NOT NULL,
    Pergunta VARCHAR2(1024),
    Resposta_correta VARCHAR2(1024),
    CONSTRAINT UNQ_Questao UNIQUE(Topico, Teste_Tema, Teste_Numero),
    CONSTRAINT PK_Questao PRIMARY KEY (Id_questao),
    FOREIGN KEY (Teste_Tema, Teste_Numero) REFERENCES Teste(Modulo_Tema,Numero)
        ON	DELETE	CASCADE
);

-- Tabela Medalha
CREATE TABLE Medalha (
    Nome VARCHAR2(32) NOT NULL,
    Teste_Tema VARCHAR2(16) NOT NULL,
    Teste_Numero INT NOT NULL,
    Descricao VARCHAR2(128),
    CONSTRAINT PK_Medalha PRIMARY KEY (Teste_Tema, Teste_Numero, Nome),
    FOREIGN KEY (Teste_Tema, Teste_Numero)
        REFERENCES Teste(Modulo_Tema, Numero)
        ON	DELETE	CASCADE
);

-- Tabela Resposta Questao
CREATE TABLE RespostaQuestao (
    Resultado NUMBER NOT NULL,
    Questao NUMBER NOT NULL,
    Resposta_Cliente VARCHAR2(1024),
    Acerto_da_Resposta NUMBER(1,0),
    CONSTRAINT PK_RespostaQuestao PRIMARY KEY (Resultado, Questao),
    FOREIGN KEY (Resultado) 
        REFERENCES Resultado(Id_resultado)
        ON	DELETE	CASCADE,
    FOREIGN KEY (Questao) REFERENCES Questao(Id_questao)
        ON	DELETE	CASCADE
);

-- Tabela Alternativa
CREATE TABLE Alternativa (
    Questao NUMBER NOT NULL,
    Numero INT NOT NULL,
    Resposta NUMBER(1,0),
    Texto VARCHAR2(512),
    CONSTRAINT PK_Alternativa PRIMARY KEY (Questao, Numero),
    FOREIGN KEY (Questao) REFERENCES Questao(Id_questao)
        ON	DELETE	CASCADE
);